//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidToolkit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string CWMRecovery { get; set; }
        public string CWMTouchRecovery { get; set; }
        public string TWRPRecovery { get; set; }
        public string DeviceImg { get; set; }
    }
}
